<?php
    include_once('modules/tminc.php');
    include('string.php');
       add_spa(
        array(
        "title"=>array(
            "hi"=>"",
            "en"=>""
        ),
        "design"=>array(
            "def"
                ),
        "css"=>array(
            "design/no_internet.css",
            "design/progress.css"
        ),
        "import"=>"nointernet"
    ));
?>
